export const countryCodeMap: Record<string, string> = {
  "United Arab Emirates": "AE",
  Spain: "ES",
  Italy: "IT",
  France: "FR",
  "United States": "US",
  Mexico: "MX",
  Brazil: "BR",
  Japan: "JP",
  Australia: "AU",
  Canada: "CA",
  Monaco: "MC",
  Belgium: "BE",
  Austria: "AT",
  Netherlands: "NL",
  Hungary: "HU",
  "United Kingdom": "GB",
  "Saudi Arabia": "SA",
  Qatar: "QA",
  Singapore: "SG",
  Bahrain: "BH",
  Argentina: "AR",
  "South Africa": "ZA",
  China: "CN",
  Russia: "RU",
};
